# Generated by Django 3.2.4 on 2021-07-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_fill_db_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='mainapp.Category', verbose_name='категории статей'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='активна'),
        ),
        migrations.AddField(
            model_name='post',
            name='on_moderation',
            field=models.BooleanField(default=False, verbose_name='на модерации'),
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=False, verbose_name='опубликована'),
        ),
        migrations.AddField(
            model_name='post',
            name='rejected',
            field=models.BooleanField(default=False, verbose_name='отменена'),
        ),
    ]
