# Generated by Django 3.2.4 on 2021-07-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210703_1546'),
        ('mainapp', '0004_auto_20210707_1347'),
    ]

    operations = [
    ]
