# Generated by Django 3.2.3 on 2021-07-08 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210707_1347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
