# Generated by Django 3.1.3 on 2021-07-03 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_authorizeduser_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizeduser',
            name='age',
        ),
    ]
