# Generated by Django 3.1.3 on 2021-07-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_remove_authorizeduser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizeduser',
            name='about_me',
            field=models.TextField(blank=True, verbose_name='о себе'),
        ),
        migrations.AddField(
            model_name='authorizeduser',
            name='age',
            field=models.PositiveSmallIntegerField(default=18, verbose_name='возвраст'),
        ),
        migrations.AddField(
            model_name='authorizeduser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users_avatars', verbose_name='аватар'),
        ),
        migrations.AddField(
            model_name='authorizeduser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'М'), ('W', 'Ж')], max_length=6, verbose_name='пол'),
        ),
    ]
